version: '3.8'

# This will run a local postgres instance for testing
# You'll need `export PGUSER=postgres` and `export PGPASSWORD=postgres123`
services:
  postgres_db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
    driver: local