name: "CI"
on:
  pull_request:
  workflow_dispatch:
  merge_group:
  push:
    branches:
      - "main"
jobs:
  check:
    name: "Build and run tests"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v3
    - name: "Install Nix"
      uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-23.05
    - name: "Install Cachix"
      uses: cachix/cachix-action@v12
      with:
        name: boulder-rust
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: "Run checks"
      run: nix flake check
