name: Build/push container

on:
  pull_request:
    branches:
    - main
    # types:
    # - closed
  workflow_dispatch:

jobs:
  build-and-push:
    name: "Build and push container image"
    if: ${{ github.event_name == 'pull_request' }} && ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    env:
      REGISTRY_URL: "${{ secrets.CONTAINER_REGISTRY_URL }}"
      IMAGE_NAME: "${{ github.repository }}:latest"
      CREDENTIALS: "${{ secrets.DIGITALOCEAN_AUTH_TOKEN }}:${{ secrets.DIGITALOCEAN_AUTH_TOKEN }}"
    permissions:
      contents: read
      packages: write
    steps:
    - name: "Checkout"
      uses: actions/checkout@v3
    - name: "Install Nix"
      uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-23.05
    - name: "Install Cachix"
      uses: cachix/cachix-action@v12
      with:
        name: boulder-rust
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: "Build and push container"
      run: nix develop -c scripts/push-container.sh ${{ env.CREDENTIALS }} ${{ env.REGISTRY_URL }} ${{ env.IMAGE_NAME }}
